import fs from 'fs';
import path from 'path';

const baseWorkspaceDir = '/workspaces/ui-g2/';
const g2ComponentsDir = path.join(baseWorkspaceDir, 'apps/www/registry/default/g2');
const targetIndexFile = path.join(g2ComponentsDir, 'index.ts');

function generateG2Exports() {
  console.log(`Scanning G2 components in: ${g2ComponentsDir}`);
  console.log(`Target index file: ${targetIndexFile}`);

  if (!fs.existsSync(g2ComponentsDir)) {
    console.error(`G2 components directory ${g2ComponentsDir} does not exist. Run the main.ts script first.`);
    return;
  }

  const files = fs.readdirSync(g2ComponentsDir);
  const componentExports: string[] = [];

  files.forEach(file => {
    if (file.endsWith('.tsx') && file !== 'index.tsx') {
      const componentName = path.basename(file, '.tsx');
      // Construct the export name based on the convention used in react-component-generator.ts
      // e.g., "algorithm-sort-bubble-sort" becomes "G2ChartComponent_algorithm_sort_bubble_sort"
      const exportName = `G2ChartComponent_${componentName.replace(/-/g, '_')}`;
      componentExports.push(`export { default as ${exportName} } from "./${componentName}";`);
    }
  });

  if (componentExports.length === 0) {
    console.log("No G2 component files found to export.");
    // Optionally, write an empty index file or one with a comment
    fs.writeFileSync(targetIndexFile, "// No G2 components found to export.\n");
    return;
  }

  const header = `// This file is auto-generated by generate-g2-exports.ts
// Do not edit this file manually.
// All G2 chart components in this directory are exported from here.

`;
  const indexContent = header + componentExports.join('\n') + '\n';

  fs.writeFileSync(targetIndexFile, indexContent);
  console.log(`Successfully generated exports in ${targetIndexFile}. Found ${componentExports.length} components.`);
}

generateG2Exports();
