import { THEMES } from "@/lib/themes"
import { ChartDisplay } from "@/components/chart-display"
import { ThemesSwitcher } from "@/components/themes-selector"
import { ThemesStyle } from "@/components/themes-styles"
import * as Charts from "@/registry/default/g2"

export default function ChartsPage() {
  return (
    <div className="grid gap-4">
      <ThemesStyle />
      <div className="gap-6 md:flex md:flex-row-reverse md:items-start">
        <ThemesSwitcher
          themes={THEMES}
          className="bg-background/95 supports-[backdrop-filter]:bg-background/60 fixed inset-x-0 bottom-0 z-40 flex backdrop-blur lg:sticky lg:bottom-auto lg:top-20"
        />
        <div className="grid flex-1 gap-12">
          <div>
            <h3>G2ChartComponent_general_pie_point_jitter_radial</h3>
            <Charts.G2ChartComponent_general_pie_point_jitter_radial />
          </div>
          <div>
            <h3>G2ChartComponent_general_polygon_treemap</h3>
            <Charts.G2ChartComponent_general_polygon_treemap />
          </div>
          <div>
            <h3>G2ChartComponent_style_graphic_radial_gradient</h3>
            <Charts.G2ChartComponent_style_graphic_radial_gradient />
          </div>
          <Charts.G2ChartComponent_general_pie_point_jitter_radial />
          <Charts.G2ChartComponent_general_polygon_treemap />
          <Charts.G2ChartComponent_style_graphic_radial_gradient />
          <Charts.G2ChartComponent_general_point_point_style />
          <Charts.G2ChartComponent_general_area_cascade_area />
          <Charts.G2ChartComponent_general_sunburst_sunburst_default />
          <Charts.G2ChartComponent_annotation_line_anomaly_area_line />
          <Charts.G2ChartComponent_algorithm_sort_insertion_sort />
          <Charts.G2ChartComponent_analysis_group_bar_stacked_diverging />
          <Charts.G2ChartComponent_unit_unit_basic />
          <Charts.G2ChartComponent_general_pie_donut />
          <Charts.G2ChartComponent_intelligent_insight_change_point />
          <Charts.G2ChartComponent_analysis_group_bar_aggregated />
          <Charts.G2ChartComponent_general_area_label />
          <Charts.G2ChartComponent_general_sunburst_sunburst_color />
          <Charts.G2ChartComponent_general_area_orderly_area />
          <Charts.G2ChartComponent_component_tooltip_tooltip_marker />
          <Charts.G2ChartComponent_annotation_shape_interval_point />
          <Charts.G2ChartComponent_graph_hierarchy_treemap />
          <Charts.G2ChartComponent_graph_hierarchy_circle_packing />
          <Charts.G2ChartComponent_general_radar_radar />
          <Charts.G2ChartComponent_composition_repeat_matrix />
          <Charts.G2ChartComponent_general_dual_multi_line_sync />
          <Charts.G2ChartComponent_component_tooltip_tooltip_render />
          <Charts.G2ChartComponent_style_graphic_line />
          <Charts.G2ChartComponent_general_heatmap_heatmap />
          <Charts.G2ChartComponent_general_pie_pie />
          <Charts.G2ChartComponent_analysis_bin_bin_size />
          <Charts.G2ChartComponent_interesting_interesting_25d_column />
          <Charts.G2ChartComponent_interesting_interesting_messi />
          <Charts.G2ChartComponent_threed_scatter_perspective_projection />
          <Charts.G2ChartComponent_component_tooltip_tooltip_crosshairs />
          <Charts.G2ChartComponent_general_parallel_line_parallel_vertical />
          <Charts.G2ChartComponent_general_histogram_histogram />
          <Charts.G2ChartComponent_general_candlestick_k_and_area />
          <Charts.G2ChartComponent_layout_layout_chart_layout />
          <Charts.G2ChartComponent_general_dual_dual_axis_line_bar />
          <Charts.G2ChartComponent_expr_base_expr />
          <Charts.G2ChartComponent_general_gauge_gauge_custom_color />
          <Charts.G2ChartComponent_general_interval_bar_range />
          <Charts.G2ChartComponent_animation_general_fade />
          <Charts.G2ChartComponent_component_legend_category />
          <Charts.G2ChartComponent_general_text_wordcloud_english />
          <Charts.G2ChartComponent_component_tooltip_tooltip_click_line />
          <Charts.G2ChartComponent_analysis_group_bar_aggregated_normalized_stacked />
          <Charts.G2ChartComponent_general_polygon_voronoi />
          <Charts.G2ChartComponent_general_area_stacked_area />
          <Charts.G2ChartComponent_general_interval_bar_marimekko />
          <Charts.G2ChartComponent_general_point_point_strip />
          <Charts.G2ChartComponent_interesting_interesting_petal />
          <Charts.G2ChartComponent_analysis_bin_binx_color />
          <Charts.G2ChartComponent_component_tooltip_tooltip_custom />
          <Charts.G2ChartComponent_general_radar_area_radial />
          <Charts.G2ChartComponent_analysis_bin_bin_color />
          <Charts.G2ChartComponent_general_vector_wind />
          <Charts.G2ChartComponent_threed_bar_cube />
          <Charts.G2ChartComponent_general_liquid_liquid_background />
          <Charts.G2ChartComponent_general_mini_column />
          <Charts.G2ChartComponent_general_violin_violin />
          <Charts.G2ChartComponent_renderer_renderer_svg />
          <Charts.G2ChartComponent_general_rose_donut_rose />
          <Charts.G2ChartComponent_general_liquid_liquid_content />
          <Charts.G2ChartComponent_intelligent_auto_auto_interval />
          <Charts.G2ChartComponent_general_radar_radial_with_background_color />
          <Charts.G2ChartComponent_general_area_percentage_area />
          <Charts.G2ChartComponent_general_sunburst_sunburst_label />
          <Charts.G2ChartComponent_annotation_shape_watermark />
          <Charts.G2ChartComponent_component_axis_axis_xy />
          <Charts.G2ChartComponent_general_link_link_shape />
          <Charts.G2ChartComponent_general_radar_complex_radial />
          <Charts.G2ChartComponent_general_dual_dual_axis_bar />
          <Charts.G2ChartComponent_general_violin_density />
          <Charts.G2ChartComponent_general_interval_bar_flex />
          <Charts.G2ChartComponent_general_text_wordcloud_mask />
          <Charts.G2ChartComponent_general_liquid_liquid_default />
          <Charts.G2ChartComponent_general_area_area_range />
          <Charts.G2ChartComponent_general_venn_venn />
          <Charts.G2ChartComponent_composition_facet_rect />
          <Charts.G2ChartComponent_general_dual_multi_line />
          <Charts.G2ChartComponent_general_pie_pie_base_facet />
          <Charts.G2ChartComponent_interaction_data_bar_normalizey_element_point_move />
          <Charts.G2ChartComponent_style_theme_academy />
          <Charts.G2ChartComponent_general_text_paragraph />
          <Charts.G2ChartComponent_general_image_icon />
          <Charts.G2ChartComponent_storytelling_storytelling_gantt />
          <Charts.G2ChartComponent_general_heatmap_heatmap_density />
          <Charts.G2ChartComponent_component_legend_continuous />
          <Charts.G2ChartComponent_style_graphic_text />
          <Charts.G2ChartComponent_composition_space_space_layer />
          <Charts.G2ChartComponent_composition_facet_circle />
          <Charts.G2ChartComponent_general_radial_apple_activity />
          <Charts.G2ChartComponent_general_area_streamgraph />
          <Charts.G2ChartComponent_general_interval_interval_style />
          <Charts.G2ChartComponent_general_interval_bar_basic_stacked />
          <Charts.G2ChartComponent_general_area_area_with_negative />
          <Charts.G2ChartComponent_intelligent_insight_low_variance />
          <Charts.G2ChartComponent_general_sunburst_sunburst_interaction />
          <Charts.G2ChartComponent_general_interval_bar_dual_axes />
          <Charts.G2ChartComponent_general_line_line_threshold />
          <Charts.G2ChartComponent_interaction_data_area_element_point_move />
          <Charts.G2ChartComponent_style_pattern_dots_pattern />
          <Charts.G2ChartComponent_general_radial_radial_line />
          <Charts.G2ChartComponent_intelligent_auto_auto_pie />
          <Charts.G2ChartComponent_general_line_step />
          <Charts.G2ChartComponent_general_box_boxplot_outlier />
          <Charts.G2ChartComponent_component_label_htmllabel />
          <Charts.G2ChartComponent_interaction_other_chart_index />
          <Charts.G2ChartComponent_analysis_bin_binx />
          <Charts.G2ChartComponent_interaction_element_select />
          <Charts.G2ChartComponent_storytelling_storytelling_interval_keyframe />
          <Charts.G2ChartComponent_composition_facet_rect_frame />
          <Charts.G2ChartComponent_general_image_logo />
          <Charts.G2ChartComponent_style_rough_point />
          <Charts.G2ChartComponent_component_label_overlaphide />
          <Charts.G2ChartComponent_general_radar_square_radar />
          <Charts.G2ChartComponent_style_pattern_squares_pattern />
          <Charts.G2ChartComponent_general_area_area_difference />
          <Charts.G2ChartComponent_general_pie_spider_label />
          <Charts.G2ChartComponent_renderer_renderer_webgl />
          <Charts.G2ChartComponent_general_bullet_bullets />
          <Charts.G2ChartComponent_general_rose_wind_rose />
          <Charts.G2ChartComponent_component_label_contrastreverse />
          <Charts.G2ChartComponent_general_box_grouped_boxplot_outlier />
          <Charts.G2ChartComponent_style_rough_line />
          <Charts.G2ChartComponent_general_box_box />
          <Charts.G2ChartComponent_general_interval_column_min_height />
          <Charts.G2ChartComponent_general_dual_pareto />
          <Charts.G2ChartComponent_geo_geo_flights_airports />
          <Charts.G2ChartComponent_annotation_connector_interval_connector />
          <Charts.G2ChartComponent_component_tooltip_tooltip_series />
          <Charts.G2ChartComponent_geo_geo_hexbin_china />
          <Charts.G2ChartComponent_interaction_data_area_normalizey_element_point_move />
          <Charts.G2ChartComponent_threed_scatter_triangle_shape />
          <Charts.G2ChartComponent_annotation_line_quadrant_scatter />
          <Charts.G2ChartComponent_annotation_shape_line_badge />
          <Charts.G2ChartComponent_general_interval_bar_fixed_cornered />
          <Charts.G2ChartComponent_general_mini_progress />
          <Charts.G2ChartComponent_style_rough_radial />
          <Charts.G2ChartComponent_general_line_line_series />
          <Charts.G2ChartComponent_storytelling_storytelling_point_keyframe />
          <Charts.G2ChartComponent_general_line_line_series_var_color />
          <Charts.G2ChartComponent_composition_facet_rect_row />
          <Charts.G2ChartComponent_general_line_line_sample />
          <Charts.G2ChartComponent_component_tooltip_tooltip_line_marker />
          <Charts.G2ChartComponent_algorithm_sort_bubble_sort />
          <Charts.G2ChartComponent_composition_facet_rect_col />
          <Charts.G2ChartComponent_general_interval_bar_basic_transposed />
          <Charts.G2ChartComponent_storytelling_storytelling_facet_keyframe />
          <Charts.G2ChartComponent_renderer_renderer_canvas />
          <Charts.G2ChartComponent_general_dual_line_bar />
          <Charts.G2ChartComponent_component_axis_axis_multi />
          <Charts.G2ChartComponent_threed_scatter_sphere_shape />
          <Charts.G2ChartComponent_annotation_line_interval_threshold />
          <Charts.G2ChartComponent_general_mini_line />
          <Charts.G2ChartComponent_analysis_regression_exponential_regression />
          <Charts.G2ChartComponent_general_area_area_basic />
          <Charts.G2ChartComponent_general_rose_rose_label />
          <Charts.G2ChartComponent_geo_geo_projection_comparison />
          <Charts.G2ChartComponent_general_point_point_sequential />
          <Charts.G2ChartComponent_unit_unit_2d />
          <Charts.G2ChartComponent_general_candlestick_basis />
          <Charts.G2ChartComponent_intelligent_insight_category_outlier />
          <Charts.G2ChartComponent_style_graphic_mark />
          <Charts.G2ChartComponent_general_area_step_area />
          <Charts.G2ChartComponent_general_line_base />
          <Charts.G2ChartComponent_algorithm_sort_selection_sort />
          <Charts.G2ChartComponent_interaction_data_line_element_point_move />
          <Charts.G2ChartComponent_interaction_component_legend />
          <Charts.G2ChartComponent_general_mini_area />
          <Charts.G2ChartComponent_component_legend_position />
          <Charts.G2ChartComponent_general_pie_pie_base />
          <Charts.G2ChartComponent_general_point_point_jitter />
          <Charts.G2ChartComponent_general_line_line_var_size_missing />
          <Charts.G2ChartComponent_annotation_text_line_text />
          <Charts.G2ChartComponent_interaction_brush_brush />
          <Charts.G2ChartComponent_general_radial_bar_radial />
          <Charts.G2ChartComponent_general_box_polar_box />
          <Charts.G2ChartComponent_annotation_line_point_line />
          <Charts.G2ChartComponent_interesting_interesting_national />
          <Charts.G2ChartComponent_component_title_title />
          <Charts.G2ChartComponent_general_bullet_bullet_datas />
          <Charts.G2ChartComponent_general_dual_dual_axis_multi_line_bar />
          <Charts.G2ChartComponent_general_venn_venn_hollow />
          <Charts.G2ChartComponent_component_tooltip_tooltip_style />
          <Charts.G2ChartComponent_component_legend_title />
          <Charts.G2ChartComponent_general_line_line_area_clip_path />
          <Charts.G2ChartComponent_general_cell_cell_aggregated />
          <Charts.G2ChartComponent_component_axis_axis_polar />
          <Charts.G2ChartComponent_component_tooltip_tooltip />
          <Charts.G2ChartComponent_threed_scatter_custom_legend />
          <Charts.G2ChartComponent_graph_network_chord />
          <Charts.G2ChartComponent_general_violin_violin_polar />
          <Charts.G2ChartComponent_general_histogram_histogram_binwidth />
          <Charts.G2ChartComponent_unit_unit_nested />
          <Charts.G2ChartComponent_general_area_area_gradient />
          <Charts.G2ChartComponent_interaction_data_column_element_point_move />
          <Charts.G2ChartComponent_general_vector_poisson />
          <Charts.G2ChartComponent_annotation_line_interval_mean_line />
          <Charts.G2ChartComponent_general_sunburst_sunburst_pattern />
          <Charts.G2ChartComponent_general_helix_helix />
          <Charts.G2ChartComponent_general_sunburst_sunburst_style />
          <Charts.G2ChartComponent_intelligent_insight_time_series_outlier />
          <Charts.G2ChartComponent_component_tooltip_tooltip_two />
          <Charts.G2ChartComponent_general_text_poetry />
          <Charts.G2ChartComponent_general_radar_parallel_radar />
          <Charts.G2ChartComponent_general_radar_grid_radial />
          <Charts.G2ChartComponent_general_area_range_spline_area />
          <Charts.G2ChartComponent_general_cell_cell_heatmap />
          <Charts.G2ChartComponent_general_funnel_funnel_annotation />
          <Charts.G2ChartComponent_general_interval_bar_stacked_diverging_rounded />
          <Charts.G2ChartComponent_style_pattern_custom_pattern_with_canvas />
          <Charts.G2ChartComponent_threed_surface_trigonometric />
          <Charts.G2ChartComponent_annotation_line_histogram_mean_line />
          <Charts.G2ChartComponent_general_line_line_style />
          <Charts.G2ChartComponent_animation_general_zoom_in />
          <Charts.G2ChartComponent_general_text_wordcloud />
          <Charts.G2ChartComponent_general_pie_spider_label_overlap />
          <Charts.G2ChartComponent_analysis_bin_poisson />
          <Charts.G2ChartComponent_component_scrollbar_scrollbar />
          <Charts.G2ChartComponent_threed_scatter_square_shape />
          <Charts.G2ChartComponent_animation_general_scale_x />
          <Charts.G2ChartComponent_animation_group_line />
          <Charts.G2ChartComponent_style_pattern_custom_pattern_with_g_api />
          <Charts.G2ChartComponent_animation_group_area />
          <Charts.G2ChartComponent_animation_general_path_in />
          <Charts.G2ChartComponent_analysis_group_bar_aggregated_with_label />
          <Charts.G2ChartComponent_general_gauge_gauge_custom_shape />
          <Charts.G2ChartComponent_component_axis_axis />
          <Charts.G2ChartComponent_general_line_line_basic />
          <Charts.G2ChartComponent_component_tooltip_tooltip_click />
          <Charts.G2ChartComponent_general_radial_radial_bar_with_background />
          <Charts.G2ChartComponent_graph_hierarchy_tree />
          <Charts.G2ChartComponent_analysis_regression_polynomial_regression />
          <Charts.G2ChartComponent_style_graphic_area />
          <Charts.G2ChartComponent_general_text_train />
          <Charts.G2ChartComponent_analysis_group_bar_stacked_normalized_1d />
          <Charts.G2ChartComponent_general_helix_helix_gene />
          <Charts.G2ChartComponent_general_line_line_var_size />
          <Charts.G2ChartComponent_general_area_missing_data_area />
          <Charts.G2ChartComponent_component_legend_custom />
          <Charts.G2ChartComponent_general_rose_stacked_rose />
          <Charts.G2ChartComponent_general_point_point_bubble />
          <Charts.G2ChartComponent_general_interval_bar_basic_grouped />
          <Charts.G2ChartComponent_general_interval_bar_normalized_stacked />
          <Charts.G2ChartComponent_annotation_range_line_range />
          <Charts.G2ChartComponent_annotation_line_point_point />
          <Charts.G2ChartComponent_general_point_point_log />
          <Charts.G2ChartComponent_general_point_point_shape />
          <Charts.G2ChartComponent_general_line_curved />
          <Charts.G2ChartComponent_storytelling_storytelling_stocks_keyframe />
          <Charts.G2ChartComponent_threed_scatter_orthographic_projection />
          <Charts.G2ChartComponent_general_interval_column_maxwidth />
          <Charts.G2ChartComponent_general_funnel_pyramid />
          <Charts.G2ChartComponent_general_box_boxplot_1d />
          <Charts.G2ChartComponent_general_interval_bar_basic />
          <Charts.G2ChartComponent_style_rough_interval />
          <Charts.G2ChartComponent_graph_network_forcegraph_disjoint />
          <Charts.G2ChartComponent_general_parallel_line_parallel_horizontal />
          <Charts.G2ChartComponent_animation_lottie_lottie />
          <Charts.G2ChartComponent_general_image_contributor />
          <Charts.G2ChartComponent_general_rose_nightingale_rose />
          <Charts.G2ChartComponent_general_area_area_stacked_basic />
          <Charts.G2ChartComponent_general_gauge_gauge_round />
          <Charts.G2ChartComponent_general_point_point_stacked />
          <Charts.G2ChartComponent_general_link_link />
          <Charts.G2ChartComponent_general_pie_pie_donut_text />
          <Charts.G2ChartComponent_intelligent_auto_auto_scatter />
          <Charts.G2ChartComponent_accessible_text_searching_text_search />
          <Charts.G2ChartComponent_general_line_line_variable_color />
          <Charts.G2ChartComponent_general_gauge_gauge_default />
          <Charts.G2ChartComponent_general_area_area_band />
          <Charts.G2ChartComponent_general_candlestick_line_candle_stick />
          <Charts.G2ChartComponent_general_area_area />
          <Charts.G2ChartComponent_style_theme_layout_area />
          <Charts.G2ChartComponent_general_interval_bar_stacked />
          <Charts.G2ChartComponent_analysis_bin_bin_opacity />
          <Charts.G2ChartComponent_general_mini_pie />
          <Charts.G2ChartComponent_general_point_point_basic />
          <Charts.G2ChartComponent_general_histogram_histogram_stacked />
          <Charts.G2ChartComponent_general_interval_column_interactive />
          <Charts.G2ChartComponent_general_rose_rose />
          <Charts.G2ChartComponent_general_funnel_funnel />
          <Charts.G2ChartComponent_component_tooltip_tooltip2d />
          <Charts.G2ChartComponent_interaction_data_bar_element_point_move />
          <Charts.G2ChartComponent_interaction_data_column_normalizey_element_point_move />
          <Charts.G2ChartComponent_general_dual_dual_aggregated_line_area />
          <Charts.G2ChartComponent_component_title_title_style />
          <Charts.G2ChartComponent_analysis_group_bar_aggregated_stacked />
          <Charts.G2ChartComponent_general_area_rank_trend_area />
          <Charts.G2ChartComponent_intelligent_insight_trend />
          <Charts.G2ChartComponent_graph_network_forcegraph />
          <Charts.G2ChartComponent_threed_scatter_circle_shape />
          <Charts.G2ChartComponent_general_heatmap_mouse_heatmap />
          <Charts.G2ChartComponent_unit_unit_share_data />
          <Charts.G2ChartComponent_interaction_data_pie_element_point_move />
          <Charts.G2ChartComponent_component_label_overflowhide />
          <Charts.G2ChartComponent_analysis_group_bar_layered />
          <Charts.G2ChartComponent_threed_surface_dirichlet />
          <Charts.G2ChartComponent_annotation_range_bar_range />
          <Charts.G2ChartComponent_general_link_link_annotation />
          <Charts.G2ChartComponent_composition_facet_rect_pie />
          <Charts.G2ChartComponent_general_interval_bar_dodged />
          <Charts.G2ChartComponent_general_rose_polar_stack />
          <Charts.G2ChartComponent_general_funnel_mirror_funnel />
          <Charts.G2ChartComponent_general_area_area_percentage />
          <Charts.G2ChartComponent_general_line_line_var_size_facet />
          <Charts.G2ChartComponent_general_interval_bar_diverging />
          <Charts.G2ChartComponent_composition_repeat_matrix_col />
          <Charts.G2ChartComponent_geo_geo_world_map />
          <Charts.G2ChartComponent_geo_geo_london_tube_lines />
          <Charts.G2ChartComponent_general_cell_cell_quantize />
          <Charts.G2ChartComponent_general_line_line_gradient_encoding />
          <Charts.G2ChartComponent_general_line_line_connect_nulls />
          <Charts.G2ChartComponent_threed_line_polyline />
          <Charts.G2ChartComponent_general_interval_bar_var_width />
          <Charts.G2ChartComponent_general_interval_bar_range_micro />
          <Charts.G2ChartComponent_general_point_point_dot />
          <Charts.G2ChartComponent_general_box_grouped_box />
          <Charts.G2ChartComponent_general_dual_dual_axis_stacked_group_bar />
          <Charts.G2ChartComponent_analysis_regression_linear_regression />
          <Charts.G2ChartComponent_component_legend_symbol />
          <Charts.G2ChartComponent_unit_unit_share_size />
          <Charts.G2ChartComponent_composition_space_space_flex />
          <Charts.G2ChartComponent_animation_group_point />
          <Charts.G2ChartComponent_general_point_point_label />
          <Charts.G2ChartComponent_annotation_range_point_range />
          <Charts.G2ChartComponent_graph_network_sankey />
          <Charts.G2ChartComponent_threed_bar_cylinder />
          <Charts.G2ChartComponent_general_cell_cell_basic />
          <Charts.G2ChartComponent_general_ema_ema_basic />
          <Charts.G2ChartComponent_general_candlestick_k_and_column />
          <Charts.G2ChartComponent_animation_group_interval />
          <Charts.G2ChartComponent_threed_bar_cone />
          <Charts.G2ChartComponent_general_mini_ring />
          <Charts.G2ChartComponent_animation_group_interval_polar />
          <Charts.G2ChartComponent_style_graphic_pattern />
          <Charts.G2ChartComponent_component_axis_axis_x />
          <Charts.G2ChartComponent_interesting_interesting_timeline />
          <Charts.G2ChartComponent_interaction_element_slider />
          <Charts.G2ChartComponent_style_theme_dark />
          <Charts.G2ChartComponent_analysis_regression_logarithmic_regression />
          <Charts.G2ChartComponent_intelligent_auto_auto_line />
          <Charts.G2ChartComponent_general_line_line_slope />
          <Charts.G2ChartComponent_analysis_group_bar_multi_measure />
          <Charts.G2ChartComponent_general_cell_cell_threshold />
          <Charts.G2ChartComponent_general_radial_bar_cornered_radial />
          <Charts.G2ChartComponent_geo_geo_choropleth_usa />
          <Charts.G2ChartComponent_general_interval_column_log />
          <Charts.G2ChartComponent_general_box_boxplot />
          <Charts.G2ChartComponent_general_interval_bar />
          <Charts.G2ChartComponent_general_bullet_bullet />
          <Charts.G2ChartComponent_general_point_point_aggregated />
          <Charts.G2ChartComponent_intelligent_insight_insight />
          <Charts.G2ChartComponent_component_legend_item_style />
          <Charts.G2ChartComponent_general_line_line_zero_values />
          <Charts.G2ChartComponent_general_liquid_liquid_custom_shape />
          <Charts.G2ChartComponent_general_point_point_one_dimension />
          <Charts.G2ChartComponent_general_line_line_normalized />
          <Charts.G2ChartComponent_component_legend_nav_style />
          <Charts.G2ChartComponent_general_cell_cell_quantile />
          <Charts.G2ChartComponent_layout_style_chart_view_style />
          <Charts.G2ChartComponent_general_radial_radial_stacked />
          <Charts.G2ChartComponent_style_pattern_lines_pattern />
          <Charts.G2ChartComponent_threed_scatter_camera_animation />
          <Charts.G2ChartComponent_general_line_line_aggregated_label />
          <Charts.G2ChartComponent_graph_hierarchy_treemap_drill_down />
          <Charts.G2ChartComponent_geo_geo_hexjson_usa />
          <Charts.G2ChartComponent_composition_facet_rect_bar />
          <Charts.G2ChartComponent_annotation_text_peak_value_text />
          <Charts.G2ChartComponent_interaction_element_highlight />
          <Charts.G2ChartComponent_interaction_data_line_element_point_move_polar />
          <Charts.G2ChartComponent_general_interval_bar_stacked_horizontal />
          <Charts.G2ChartComponent_threed_line_spiral />
          <Charts.G2ChartComponent_interaction_multi_view_focus_context />
          <Charts.G2ChartComponent_general_pie_donut_base />
          <Charts.G2ChartComponent_animation_general_scale_y />
          <Charts.G2ChartComponent_annotation_connector_revenue_flow_waterfall />
          <Charts.G2ChartComponent_interaction_other_fisheye />
          <Charts.G2ChartComponent_analysis_regression_quadratic_regression />
          <Charts.G2ChartComponent_animation_general_wave_in />
          <Charts.G2ChartComponent_interaction_brush_brush_emit />
          <Charts.G2ChartComponent_general_liquid_liquid_pin />
          <Charts.G2ChartComponent_style_graphic_gauge />
        </div>
      </div>
    </div>
  )
}
